# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
# Print the dimension (number of axes) of A
print("Dimension (number of axes):", A.ndim)

# Print the shape (number of rows and columns) of A
print("Shape:", A.shape)

# Print the size (total number of elements) of A
print("Size:", A.size)

# Print the datatype of A
print("Datatype:", A.dtype)

Dimension (number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [5]:
# Elementwise subtraction
elementwise_subtraction = B - C
print("Elementwise Subtraction:")
print(elementwise_subtraction)

# Elementwise multiplication
elementwise_multiplication = B * C
print("\nElementwise Multiplication:")
print(elementwise_multiplication)

# Matrix multiplication
matrix_multiplication = B @ C
print("\nMatrix Multiplication:")
print(matrix_multiplication)

Elementwise Subtraction:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise Multiplication:
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication:
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Exponentiate each number elementwise
exponentiated_matrix = np.exp(B)
print("\nExponentiated Matrix:")
print(exponentiated_matrix)

# Calculate the minimum value in the whole matrix
min_value = np.min(B)
print("\nMinimum Value in the Whole Matrix:", min_value)

# Calculate the minimum value in each row
min_values_in_rows = np.min(B, axis=1)
print("\nMinimum Value in Each Row:")
print(min_values_in_rows)

# Calculate the minimum value in each column
min_values_in_columns = np.min(B, axis=0)
print("\nMinimum Value in Each Column:")
print(min_values_in_columns)

# Find the index value for the minimum value in the whole matrix
min_index = np.argmin(B)
min_index_row, min_index_col = np.unravel_index(min_index, B.shape)
print("\nIndex Value for the Minimum Value in the Whole Matrix (Row, Column):", min_index_row, min_index_col)

# Find the index value for the minimum value in each row
min_indices_in_rows = np.argmin(B, axis=1)
print("\nIndex Values for the Minimum Value in Each Row:")
print(min_indices_in_rows)

# Calculate the sum for all elements
sum_of_elements = np.sum(B)
print("\nSum of All Elements:", sum_of_elements)

# Calculate the mean for each column
mean_of_columns = np.mean(B, axis=0)
print("\nMean for Each Column:")
print(mean_of_columns)

# Calculate the median for each column
median_of_columns = np.median(B, axis=0)
print("\nMedian for Each Column:")
print(median_of_columns)


Exponentiated Matrix:
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum Value in the Whole Matrix: 1

Minimum Value in Each Row:
[1 4 7]

Minimum Value in Each Column:
[1 2 3]

Index Value for the Minimum Value in the Whole Matrix (Row, Column): 0 0

Index Values for the Minimum Value in Each Row:
[0 0 0]

Sum of All Elements: 45

Mean for Each Column:
[4. 5. 6.]

Median for Each Column:
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [10]:
"""
    The array A is being printed first. Then, you are using basic slicing with A[1], which means you want to extract the second row (index 1) from the array A. This operation returns a 1D subarray containing the elements of the second row of A.

    In NumPy, if you provide fewer indices than axes during slicing, the array is sliced along the specified axis, and you get a view of the data with reduced dimensionality. In this case, you're reducing a 2D array (matrix) to a 1D array (vector) by slicing along the rows.
"""

"\n    The array A is being printed first. Then, you are using basic slicing with A[1], which means you want to extract the second row (index 1) from the array A. This operation returns a 1D subarray containing the elements of the second row of A.\n\n    In NumPy, if you provide fewer indices than axes during slicing, the array is sliced along the specified axis, and you get a view of the data with reduced dimensionality. In this case, you're reducing a 2D array (matrix) to a 1D array (vector) by slicing along the rows.\n"

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [13]:
# You can use nested loops to traverse all elements in the array. 
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Iterate through the array element-wise
for row in A:
    for element in row:
        print(element)

1
2
3
4
5
6
7
8
9


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [15]:
"""

    The term "axes" in the context of NumPy arrays refers to the dimensions of the array. The array b has three axes because it is a 3D array. Each axis represents a different dimension:

    The first axis (axis 0) has a size of 2, corresponding to the first dimension.
    The second axis (axis 1) has a size of 3, corresponding to the second dimension.
    The third axis (axis 2) has a size of 5, corresponding to the third dimension.

"""

'\n\n    The term "axes" in the context of NumPy arrays refers to the dimensions of the array. The array b has three axes because it is a 3D array. Each axis represents a different dimension:\n\n    The first axis (axis 0) has a size of 2, corresponding to the first dimension.\n    The second axis (axis 1) has a size of 3, corresponding to the second dimension.\n    The third axis (axis 2) has a size of 5, corresponding to the third dimension.\n\n'

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [16]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [17]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [18]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.8, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.15, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [19]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [20]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that both input matrices are of type numpy.ndarray
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both input matrices must be of type numpy.ndarray")

    if operation == 'add':
        # Validate that the matrices have the same shape for addition
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        result = matrix1 + matrix2
    elif operation == 'multiply':
        # Validate that the matrix sizes conform for multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Matrix sizes do not conform for multiplication")
        result = np.dot(matrix1, matrix2)
    else:
        raise ValueError("Invalid operation. Use 'add' or 'multiply' as the operation.")

    return result

# Example usage:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
result_add = add_mult_matrices(matrix_a, matrix_b, 'add')
result_multiply = add_mult_matrices(matrix_a, matrix_b, 'multiply')

print("Matrix A:")
print(matrix_a)
print("Matrix B:")
print(matrix_b)
print("Result of Addition:")
print(result_add)
print("Result of Multiplication:")
print(result_multiply)


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Result of Addition:
[[ 6  8]
 [10 12]]
Result of Multiplication:
[[19 22]
 [43 50]]


**Chap2. Question 2**

In [21]:
import numpy as np

# Define Matrix A
A = np.array([[1, -1],
              [-1, 1]])

# Define Matrix B
B = np.array([[-1, 1],
              [1, -1]])

# Calculate the matrix product
C = np.dot(A, B)

# Print the resulting matrix C
print(C)


[[-2  2]
 [ 2 -2]]


**Chap2. Question 3**

In [22]:
import numpy as np

# Define the size of the matrices
n = 4

# Create upper triangular matrices A and B
A = np.triu(np.random.randint(1, 5, (n, n)), 0)
B = np.triu(np.random.randint(1, 5, (n, n)), 0)

# Initialize the product matrix AB
AB = np.zeros((n, n))

# Calculate the matrix product (AB)ij
for i in range(n):
    for j in range(n):
        for k in range(i + 1):
            AB[i, j] += A[i, k] * B[k, j]

# Print matrices A, B, and the resulting AB
print("Matrix A (Upper Triangular):")
print(A)
print("\nMatrix B (Upper Triangular):")
print(B)
print("\nMatrix AB (Result of AB):")
print(AB)


Matrix A (Upper Triangular):
[[2 3 3 1]
 [0 2 3 3]
 [0 0 4 1]
 [0 0 0 1]]

Matrix B (Upper Triangular):
[[3 3 3 4]
 [0 4 4 1]
 [0 0 3 3]
 [0 0 0 4]]

Matrix AB (Result of AB):
[[ 6.  6.  6.  8.]
 [ 0.  8.  8.  2.]
 [ 0.  0. 12. 12.]
 [ 0.  0.  0.  4.]]


**Quiz p.11, Question 2**

In [23]:
import numpy as np

# Create a random square matrix A
n = 4  # Size of the matrix
A = np.random.randint(1, 10, (n, n))

# Calculate the symmetric matrix A_s
A_s = 0.5 * (A + A.T)

# Calculate the skew-symmetric matrix A_k
A_k = 0.5 * (A - A.T)

# Verify that A = A_s + A_k
sum_matrix = A_s + A_k

# Print the matrices
print("Matrix A:")
print(A)
print("\nSymmetric Matrix A_s:")
print(A_s)
print("\nSkew-Symmetric Matrix A_k:")
print(A_k)
print("\nA = A_s + A_k:")
print(sum_matrix)


Matrix A:
[[3 8 7 4]
 [1 3 4 9]
 [7 2 8 4]
 [9 3 8 9]]

Symmetric Matrix A_s:
[[3.  4.5 7.  6.5]
 [4.5 3.  3.  6. ]
 [7.  3.  8.  6. ]
 [6.5 6.  6.  9. ]]

Skew-Symmetric Matrix A_k:
[[ 0.   3.5  0.  -2.5]
 [-3.5  0.   1.   3. ]
 [ 0.  -1.   0.  -2. ]
 [ 2.5 -3.   2.   0. ]]

A = A_s + A_k:
[[3. 8. 7. 4.]
 [1. 3. 4. 9.]
 [7. 2. 8. 4.]
 [9. 3. 8. 9.]]


**Chap 6. Question 1**

In [24]:
import numpy as np

# Define the matrices
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])

# Calculate the inverses
A_inverse = np.linalg.inv(A)
B_inverse = np.linalg.inv(B)

# Print the inverse matrices
print("Inverse of Matrix A:")
print(A_inverse)
print("\nInverse of Matrix B:")
print(B_inverse)


Inverse of Matrix A:
[[ 5. -6.]
 [-4.  5.]]

Inverse of Matrix B:
[[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3**

In [25]:
# Define the angle of rotation (in radians)
theta = np.pi / 4  # Rotate by 45 degrees (pi/4 radians)

# Create the z-rotation matrix
Rz = np.array([[np.cos(theta), -np.sin(theta), 0],
              [np.sin(theta), np.cos(theta), 0],
              [0, 0, 1]])

# Print the rotation matrix
print("Rotation Matrix (Rz):")
print(Rz)

Rotation Matrix (Rz):
[[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


**Chap10. Question 1 a)**

In [26]:
import numpy as np

# Define the matrices
matrix_a = np.array([[0, 1], [-1, 0]])
matrix_b = np.array([[1, 0], [0, -1]])
matrix_c = np.array([[0, 1], [1, 0]])
matrix_d = np.array([[1, -1], [0, 0]])

# Check orthogonality
def is_orthogonal(matrix):
    return np.allclose(np.dot(matrix, matrix.T), np.eye(len(matrix)))

# Check orthogonality of each matrix
is_orthogonal_a = is_orthogonal(matrix_a)
is_orthogonal_b = is_orthogonal(matrix_b)
is_orthogonal_c = is_orthogonal(matrix_c)
is_orthogonal_d = is_orthogonal(matrix_d)

# Print the results
print("Matrix a) is orthogonal:", is_orthogonal_a)
print("Matrix b) is orthogonal:", is_orthogonal_b)
print("Matrix c) is orthogonal:", is_orthogonal_c)
print("Matrix d) is orthogonal:", is_orthogonal_d)


Matrix a) is orthogonal: True
Matrix b) is orthogonal: True
Matrix c) is orthogonal: True
Matrix d) is orthogonal: False


**Chap10. Question 1 b)**

In [27]:
import numpy as np

# Define the given matrices
matrix_a = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])
matrix_b = np.array([[0, 0, 1], [1, 0, 0], [0, 1, 0]])
matrix_c = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]])
matrix_d = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]])

# Define a row permutation
row_permutation = np.array([[0, 1, 0], [0, 0, 1], [1, 0, 0]])

# Function to check if a matrix performs the specified row permutation
def performs_row_permutation(matrix, row_permutation):
    return np.array_equal(np.dot(matrix, row_permutation), matrix)

# Check each matrix
matrix_a_result = performs_row_permutation(matrix_a, row_permutation)
matrix_b_result = performs_row_permutation(matrix_b, row_permutation)
matrix_c_result = performs_row_permutation(matrix_c, row_permutation)
matrix_d_result = performs_row_permutation(matrix_d, row_permutation)

# Print the results
print("Matrix a) performs the row permutation:", matrix_a_result)
print("Matrix b) performs the row permutation:", matrix_b_result)
print("Matrix c) performs the row permutation:", matrix_c_result)
print("Matrix d) performs the row permutation:", matrix_d_result)


Matrix a) performs the row permutation: False
Matrix b) performs the row permutation: False
Matrix c) performs the row permutation: False
Matrix d) performs the row permutation: False


**Chap 12. Question 1**

In [28]:
import numpy as np

# Define the matrix
matrix = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])

# Calculate the inverse
matrix_inverse = np.linalg.inv(matrix)

print("Inverse of the matrix:")
print(matrix_inverse)


Inverse of the matrix:
[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [29]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [30]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [31]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [32]:
"""
    The v1.base will return None because v1 is the original array created by np.arange(4). 
    The v2.base will return v1 because v2 is a view of the last two elements of v1. 
    Since v2 is a view, modifying it will also change the corresponding elements in v1. 
    Therefore, the last element in v1 will be changed to 123, as mentioned.
"""

'\n    The v1.base will return None because v1 is the original array created by np.arange(4). \n    The v2.base will return v1 because v2 is a view of the last two elements of v1. \n    Since v2 is a view, modifying it will also change the corresponding elements in v1. \n    Therefore, the last element in v1 will be changed to 123, as mentioned.\n'